# GCP Configuration
gcp:
  project_id: "your-gcp-project-id"  # Replace with your GCP project ID
  credentials_file: "secrets/gcp-credentials.json"
  
  # Cloud Storage
  storage:
    bucket_name: "traffic-monitor-data"
    video_samples_folder: "video_samples"
    detection_data_folder: "detection_data"
  
  # BigQuery
  bigquery:
    dataset_id: "traffic_analytics"
    vehicles_table: "vehicle_detections"
    hourly_table: "hourly_counts"
    daily_table: "daily_counts"
  
  # Sync settings
  sync:
    interval_minutes: 15
    max_retry_attempts: 5
    retry_delay_seconds: 30
    batch_size: 100